<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-24T12:47:30 IST" name="Default suite" finished-at="2024-03-24T12:48:11 IST" duration-ms="40595">
    <groups>
    </groups>
    <test started-at="2024-03-24T12:47:30 IST" name="Default test" finished-at="2024-03-24T12:48:11 IST" duration-ms="40595">
      <class name="TestScript.TroubleTicketModule">
        <test-method is-config="true" signature="DBConfig()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:30 IST" name="DBConfig" finished-at="2024-03-24T12:47:30 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBConfig -->
        <test-method is-config="true" signature="BrowserLaunch()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:31 IST" name="BrowserLaunch" finished-at="2024-03-24T12:47:35 IST" duration-ms="4041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserLaunch -->
        <test-method is-config="true" signature="LogIntoApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:35 IST" name="LogIntoApp" finished-at="2024-03-24T12:47:40 IST" duration-ms="4913" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIntoApp -->
        <test-method retried="true" signature="TroubleTicketModuleTest()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:40 IST" name="TroubleTicketModuleTest" finished-at="2024-03-24T12:47:40 IST" duration-ms="24" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestScript.TroubleTicketModule.TroubleTicketModuleTest(TroubleTicketModule.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TroubleTicketModuleTest -->
        <test-method is-config="true" signature="signoutApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:40 IST" name="signoutApp" finished-at="2024-03-24T12:47:47 IST" duration-ms="6969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signoutApp -->
        <test-method is-config="true" signature="LogIntoApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:47 IST" name="LogIntoApp" finished-at="2024-03-24T12:47:52 IST" duration-ms="5075" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIntoApp -->
        <test-method retried="true" signature="TroubleTicketModuleTest()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:52 IST" name="TroubleTicketModuleTest" finished-at="2024-03-24T12:47:52 IST" duration-ms="4" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestScript.TroubleTicketModule.TroubleTicketModuleTest(TroubleTicketModule.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TroubleTicketModuleTest -->
        <test-method is-config="true" signature="signoutApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:52 IST" name="signoutApp" finished-at="2024-03-24T12:47:59 IST" duration-ms="6976" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signoutApp -->
        <test-method is-config="true" signature="LogIntoApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:47:59 IST" name="LogIntoApp" finished-at="2024-03-24T12:48:03 IST" duration-ms="4650" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIntoApp -->
        <test-method signature="TroubleTicketModuleTest()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:48:03 IST" name="TroubleTicketModuleTest" finished-at="2024-03-24T12:48:03 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestScript.TroubleTicketModule.TroubleTicketModuleTest(TroubleTicketModule.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TroubleTicketModuleTest -->
        <test-method is-config="true" signature="signoutApp()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:48:04 IST" name="signoutApp" finished-at="2024-03-24T12:48:11 IST" duration-ms="6973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signoutApp -->
        <test-method is-config="true" signature="BrowserClose()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:48:11 IST" name="BrowserClose" finished-at="2024-03-24T12:48:11 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserClose -->
        <test-method is-config="true" signature="DBClose()[pri:0, instance:TestScript.TroubleTicketModule@1349883]" started-at="2024-03-24T12:48:11 IST" name="DBClose" finished-at="2024-03-24T12:48:11 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBClose -->
      </class> <!-- TestScript.TroubleTicketModule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
